version: "3"
services:
  service:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    command: bash -c "npm i && npm run build && npm run start:prod"
    depends_on:
      - "postgres"
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Abcd1234
      - POSTGRES_USER=alibagheri
    ports:
      - "5432:5432"


