version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Abcd1234
      - POSTGRES_USER=alibagheri
    ports:
      - "5432:5432"


